apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /docker-entrypoint.d/script.sh
          name: entrypoint-scripts
      volumes:
      - name: entrypoint-scripts
        hostPath:
          path: /Users/fenton/repos/docker-to-kubernetes/script.sh
          type: File
